version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${DJANGO_CONTAINER_PORT}
    volumes:
      - .:/api-with-django-graphql
      - /static:/static
    expose:
      - ${DJANGO_CONTAINER_PORT}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  static_volume:
  data: