version: "3.9"

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:${DJANGO_CONTAINER_PORT}
    volumes:
      - .:/graph-with-django-graphene
    ports:
      - ${DJANGO_HOST_PORT}:${DJANGO_CONTAINER_PORT}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}